# Generated by Django 5.2.9 on 2025-12-11 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_businessarea_options_alter_companycode_options_and_more'),
        ('employee', '0003_jobhistory_employee_nid'),
        ('leave', '0003_alter_employeeleavequota_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeleavequota',
            options={},
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved',
        ),
        migrations.AddField(
            model_name='employeeleavequota',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='employeeleavequota',
            unique_together={('employee', 'leave_type', 'year')},
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('daily_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('is_overnight', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('business_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='company.businessarea')),
            ],
        ),
    ]
