# Generated by Django 5.2.9 on 2025-12-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_options_alter_breakrecord_options_and_more'),
        ('employee', '0002_alter_department_options_alter_designation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
